import type { Advert } from "@/services/api/api-my-ads"

export const mockAdverts: Advert[] = [
  {
    id: "00000001",
    name: "Mariana Rueda",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=1",
    rating: 4.3,
    orders: 43,
    completion: 98,
    following: true,
    online: true,
    rate: 14500.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000002",
    name: "Pavitra Yoganathan",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=2",
    rating: 4.0,
    orders: 3,
    completion: 43,
    following: false,
    online: true,
    rate: 14600.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000003",
    name: "Farid",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=3",
    rating: 0.0,
    orders: 0,
    completion: 0,
    following: true,
    online: false,
    rate: 12500.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000004",
    name: "Lipika Sethi",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=4",
    rating: 3.2,
    orders: 40,
    completion: 94,
    following: false,
    online: true,
    rate: 11354.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000005",
    name: "Riddhi Deven",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=5",
    rating: 4.1,
    orders: 65,
    completion: 89,
    following: false,
    online: true,
    rate: 16444.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000006",
    name: "Reeja Vasu",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=6",
    rating: 3.9,
    orders: 34,
    completion: 87,
    following: true,
    online: true,
    rate: 15322.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000007",
    name: "Ameerul Hady",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=7",
    rating: 2.8,
    orders: 54,
    completion: 99,
    following: false,
    online: true,
    rate: 12444.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "buy",
  },
  {
    id: "00000008",
    name: "Jane Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=8",
    rating: 4.5,
    orders: 120,
    completion: 97,
    following: false,
    online: true,
    rate: 14300.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "sell",
  },
  {
    id: "00000009",
    name: "John Doe",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=9",
    rating: 4.7,
    orders: 85,
    completion: 99,
    following: true,
    online: true,
    rate: 14200.0,
    limits: "USD 10.00 - 100.00",
    minAmount: 10,
    maxAmount: 100,
    time: "15 min",
    methods: ["Bank transfer", "Neteller", "PayPal"],
    currency: "IDR",
    type: "sell",
  },
]

